# Generated by Django 4.0.2 on 2022-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
    ]
