# Generated by Django 4.0.2 on 2022-02-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_report_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='last_email_sent',
            field=models.TimeField(null=True),
        ),
    ]
