# Generated by Django 4.0.2 on 2022-02-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_report_last_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='last_email_sent',
            field=models.TimeField(default=None, null=True),
        ),
    ]
