# Generated by Django 4.0.2 on 2022-02-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_report_last_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='last_email_sent',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
