# Generated by Django 4.0.2 on 2022-02-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_report_last_email_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='last_email_sent',
            new_name='last_sent_day',
        ),
    ]
