# Generated by Django 4.0.2 on 2022-02-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_rename_last_email_sent_report_last_sent_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='last_sent_day',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
